// <auto-generated />
using System;
using Konya_Zoltan_Proiect_Managementul_Concediilor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konya_Zoltan_Proiect_Managementul_Concediilor.Migrations
{
    [DbContext(typeof(Konya_Zoltan_Proiect_Managementul_ConcediilorContext))]
    [Migration("20231229185218_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Angajat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adress")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("DepartamentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("FunctieID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartamentID");

                    b.HasIndex("FunctieID");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.CategorieCerere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NrCategorieCerere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeCategorieCerere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CategorieCerere");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Cerere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("AngajatID")
                        .HasColumnType("int");

                    b.Property<int?>("CategorieCerereID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FunctieID")
                        .HasColumnType("int");

                    b.Property<int?>("StareCerereID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AngajatID");

                    b.HasIndex("CategorieCerereID");

                    b.HasIndex("DepartamentID");

                    b.HasIndex("FunctieID");

                    b.HasIndex("StareCerereID");

                    b.ToTable("Cerere");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Departament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NrDepartament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeDepartament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Functie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NrFunctie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeFunctie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Functie");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.StareCerere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NrStareCerere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeStareCerere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StareCerere");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Angajat", b =>
                {
                    b.HasOne("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Departament", "Departament")
                        .WithMany("Angajati")
                        .HasForeignKey("DepartamentID");

                    b.HasOne("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Functie", "Functie")
                        .WithMany()
                        .HasForeignKey("FunctieID");

                    b.Navigation("Departament");

                    b.Navigation("Functie");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Cerere", b =>
                {
                    b.HasOne("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Angajat", "Angajat")
                        .WithMany()
                        .HasForeignKey("AngajatID");

                    b.HasOne("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.CategorieCerere", "CategorieCerere")
                        .WithMany()
                        .HasForeignKey("CategorieCerereID");

                    b.HasOne("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentID");

                    b.HasOne("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Functie", "Functie")
                        .WithMany()
                        .HasForeignKey("FunctieID");

                    b.HasOne("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.StareCerere", "StareCerere")
                        .WithMany()
                        .HasForeignKey("StareCerereID");

                    b.Navigation("Angajat");

                    b.Navigation("CategorieCerere");

                    b.Navigation("Departament");

                    b.Navigation("Functie");

                    b.Navigation("StareCerere");
                });

            modelBuilder.Entity("Konya_Zoltan_Proiect_Managementul_Concediilor.Models.Departament", b =>
                {
                    b.Navigation("Angajati");
                });
#pragma warning restore 612, 618
        }
    }
}
